// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy
{
    public static class GetProjects
    {
        /// <summary>
        /// Provides information about existing projects.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Octopusdeploy = Pulumi.Octopusdeploy;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Octopusdeploy.GetProjects.Invoke(new()
        ///     {
        ///         ClonedFromProjectId = "Projects-456",
        ///         Ids = new[]
        ///         {
        ///             "Projects-123",
        ///             "Projects-321",
        ///         },
        ///         IsClone = true,
        ///         Name = "Default",
        ///         PartialName = "Defau",
        ///         Skip = 5,
        ///         Take = 100,
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetProjectsResult> InvokeAsync(GetProjectsArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetProjectsResult>("octopusdeploy:index/getProjects:getProjects", args ?? new GetProjectsArgs(), options.WithDefaults());

        /// <summary>
        /// Provides information about existing projects.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using Pulumi;
        /// using Octopusdeploy = Pulumi.Octopusdeploy;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var example = Octopusdeploy.GetProjects.Invoke(new()
        ///     {
        ///         ClonedFromProjectId = "Projects-456",
        ///         Ids = new[]
        ///         {
        ///             "Projects-123",
        ///             "Projects-321",
        ///         },
        ///         IsClone = true,
        ///         Name = "Default",
        ///         PartialName = "Defau",
        ///         Skip = 5,
        ///         Take = 100,
        ///     });
        /// 
        /// });
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetProjectsResult> Invoke(GetProjectsInvokeArgs? args = null, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetProjectsResult>("octopusdeploy:index/getProjects:getProjects", args ?? new GetProjectsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetProjectsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A filter to search for cloned resources by a project ID.
        /// </summary>
        [Input("clonedFromProjectId")]
        public string? ClonedFromProjectId { get; set; }

        [Input("ids")]
        private List<string>? _ids;

        /// <summary>
        /// A filter to search by a list of IDs.
        /// </summary>
        public List<string> Ids
        {
            get => _ids ?? (_ids = new List<string>());
            set => _ids = value;
        }

        /// <summary>
        /// A filter to search for cloned resources.
        /// </summary>
        [Input("isClone")]
        public bool? IsClone { get; set; }

        /// <summary>
        /// A filter to search by name.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// A filter to search by the partial match of a name.
        /// </summary>
        [Input("partialName")]
        public string? PartialName { get; set; }

        [Input("projects")]
        private List<Inputs.GetProjectsProjectArgs>? _projects;

        /// <summary>
        /// A list of projects that match the filter(s).
        /// </summary>
        public List<Inputs.GetProjectsProjectArgs> Projects
        {
            get => _projects ?? (_projects = new List<Inputs.GetProjectsProjectArgs>());
            set => _projects = value;
        }

        /// <summary>
        /// A filter to specify the number of items to skip in the response.
        /// </summary>
        [Input("skip")]
        public int? Skip { get; set; }

        /// <summary>
        /// A filter to specify the number of items to take (or return) in the response.
        /// </summary>
        [Input("take")]
        public int? Take { get; set; }

        public GetProjectsArgs()
        {
        }
        public static new GetProjectsArgs Empty => new GetProjectsArgs();
    }

    public sealed class GetProjectsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// A filter to search for cloned resources by a project ID.
        /// </summary>
        [Input("clonedFromProjectId")]
        public Input<string>? ClonedFromProjectId { get; set; }

        [Input("ids")]
        private InputList<string>? _ids;

        /// <summary>
        /// A filter to search by a list of IDs.
        /// </summary>
        public InputList<string> Ids
        {
            get => _ids ?? (_ids = new InputList<string>());
            set => _ids = value;
        }

        /// <summary>
        /// A filter to search for cloned resources.
        /// </summary>
        [Input("isClone")]
        public Input<bool>? IsClone { get; set; }

        /// <summary>
        /// A filter to search by name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// A filter to search by the partial match of a name.
        /// </summary>
        [Input("partialName")]
        public Input<string>? PartialName { get; set; }

        [Input("projects")]
        private InputList<Inputs.GetProjectsProjectInputArgs>? _projects;

        /// <summary>
        /// A list of projects that match the filter(s).
        /// </summary>
        public InputList<Inputs.GetProjectsProjectInputArgs> Projects
        {
            get => _projects ?? (_projects = new InputList<Inputs.GetProjectsProjectInputArgs>());
            set => _projects = value;
        }

        /// <summary>
        /// A filter to specify the number of items to skip in the response.
        /// </summary>
        [Input("skip")]
        public Input<int>? Skip { get; set; }

        /// <summary>
        /// A filter to specify the number of items to take (or return) in the response.
        /// </summary>
        [Input("take")]
        public Input<int>? Take { get; set; }

        public GetProjectsInvokeArgs()
        {
        }
        public static new GetProjectsInvokeArgs Empty => new GetProjectsInvokeArgs();
    }


    [OutputType]
    public sealed class GetProjectsResult
    {
        /// <summary>
        /// A filter to search for cloned resources by a project ID.
        /// </summary>
        public readonly string? ClonedFromProjectId;
        /// <summary>
        /// An auto-generated identifier that includes the timestamp when this data source was last modified.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// A filter to search by a list of IDs.
        /// </summary>
        public readonly ImmutableArray<string> Ids;
        /// <summary>
        /// A filter to search for cloned resources.
        /// </summary>
        public readonly bool? IsClone;
        /// <summary>
        /// A filter to search by name.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// A filter to search by the partial match of a name.
        /// </summary>
        public readonly string? PartialName;
        /// <summary>
        /// A list of projects that match the filter(s).
        /// </summary>
        public readonly ImmutableArray<Outputs.GetProjectsProjectResult> Projects;
        /// <summary>
        /// A filter to specify the number of items to skip in the response.
        /// </summary>
        public readonly int? Skip;
        /// <summary>
        /// A filter to specify the number of items to take (or return) in the response.
        /// </summary>
        public readonly int? Take;

        [OutputConstructor]
        private GetProjectsResult(
            string? clonedFromProjectId,

            string id,

            ImmutableArray<string> ids,

            bool? isClone,

            string? name,

            string? partialName,

            ImmutableArray<Outputs.GetProjectsProjectResult> projects,

            int? skip,

            int? take)
        {
            ClonedFromProjectId = clonedFromProjectId;
            Id = id;
            Ids = ids;
            IsClone = isClone;
            Name = name;
            PartialName = partialName;
            Projects = projects;
            Skip = skip;
            Take = take;
        }
    }
}
