// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class DeploymentProcessStepAction
    {
        public readonly Outputs.DeploymentProcessStepActionActionTemplate? ActionTemplate;
        public readonly string ActionType;
        public readonly bool? CanBeUsedForProjectVersioning;
        public readonly ImmutableArray<string> Channels;
        public readonly string? Condition;
        public readonly ImmutableArray<Outputs.DeploymentProcessStepActionContainer> Containers;
        public readonly ImmutableArray<string> Environments;
        public readonly ImmutableArray<string> ExcludedEnvironments;
        public readonly ImmutableArray<string> Features;
        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        public readonly string? Id;
        public readonly bool? IsDisabled;
        public readonly bool? IsRequired;
        public readonly string Name;
        public readonly string? Notes;
        public readonly ImmutableArray<Outputs.DeploymentProcessStepActionPackage> Packages;
        public readonly Outputs.DeploymentProcessStepActionPrimaryPackage? PrimaryPackage;
        public readonly ImmutableDictionary<string, string>? Properties;
        public readonly bool? RunOnServer;
        public readonly ImmutableArray<string> TenantTags;
        public readonly string? WorkerPoolId;
        public readonly string? WorkerPoolVariable;

        [OutputConstructor]
        private DeploymentProcessStepAction(
            Outputs.DeploymentProcessStepActionActionTemplate? actionTemplate,

            string actionType,

            bool? canBeUsedForProjectVersioning,

            ImmutableArray<string> channels,

            string? condition,

            ImmutableArray<Outputs.DeploymentProcessStepActionContainer> containers,

            ImmutableArray<string> environments,

            ImmutableArray<string> excludedEnvironments,

            ImmutableArray<string> features,

            string? id,

            bool? isDisabled,

            bool? isRequired,

            string name,

            string? notes,

            ImmutableArray<Outputs.DeploymentProcessStepActionPackage> packages,

            Outputs.DeploymentProcessStepActionPrimaryPackage? primaryPackage,

            ImmutableDictionary<string, string>? properties,

            bool? runOnServer,

            ImmutableArray<string> tenantTags,

            string? workerPoolId,

            string? workerPoolVariable)
        {
            ActionTemplate = actionTemplate;
            ActionType = actionType;
            CanBeUsedForProjectVersioning = canBeUsedForProjectVersioning;
            Channels = channels;
            Condition = condition;
            Containers = containers;
            Environments = environments;
            ExcludedEnvironments = excludedEnvironments;
            Features = features;
            Id = id;
            IsDisabled = isDisabled;
            IsRequired = isRequired;
            Name = name;
            Notes = notes;
            Packages = packages;
            PrimaryPackage = primaryPackage;
            Properties = properties;
            RunOnServer = runOnServer;
            TenantTags = tenantTags;
            WorkerPoolId = workerPoolId;
            WorkerPoolVariable = workerPoolVariable;
        }
    }
}
