// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class GetChannelsChannelResult
    {
        /// <summary>
        /// The description of this channel.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Indicates if this is the default channel for the associated project.
        /// </summary>
        public readonly bool IsDefault;
        /// <summary>
        /// The lifecycle ID associated with this channel.
        /// </summary>
        public readonly string LifecycleId;
        /// <summary>
        /// The name of this resource.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The project ID associated with this channel.
        /// </summary>
        public readonly string ProjectId;
        /// <summary>
        /// A list of rules associated with this channel.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetChannelsChannelRuleResult> Rules;
        /// <summary>
        /// The space ID associated with this resource.
        /// </summary>
        public readonly string SpaceId;
        /// <summary>
        /// A list of tenant tags associated with this resource.
        /// </summary>
        public readonly ImmutableArray<string> TenantTags;

        [OutputConstructor]
        private GetChannelsChannelResult(
            string description,

            string id,

            bool isDefault,

            string lifecycleId,

            string name,

            string projectId,

            ImmutableArray<Outputs.GetChannelsChannelRuleResult> rules,

            string spaceId,

            ImmutableArray<string> tenantTags)
        {
            Description = description;
            Id = id;
            IsDefault = isDefault;
            LifecycleId = lifecycleId;
            Name = name;
            ProjectId = projectId;
            Rules = rules;
            SpaceId = spaceId;
            TenantTags = tenantTags;
        }
    }
}
