// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class GetGitCredentialsGitCredentialResult
    {
        /// <summary>
        /// The description of this Git credential.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the Git credential. This name must be unique.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The password for the Git credential.
        /// </summary>
        public readonly string Password;
        /// <summary>
        /// The space ID associated with this resource.
        /// </summary>
        public readonly string SpaceId;
        /// <summary>
        /// The Git credential authentication type.
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// The username for the Git credential.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private GetGitCredentialsGitCredentialResult(
            string description,

            string id,

            string name,

            string password,

            string spaceId,

            string type,

            string username)
        {
            Description = description;
            Id = id;
            Name = name;
            Password = password;
            SpaceId = spaceId;
            Type = type;
            Username = username;
        }
    }
}
