// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class GetListeningTentacleDeploymentTargetsListeningTentacleDeploymentTargetResult
    {
        public readonly string CertificateSignatureAlgorithm;
        /// <summary>
        /// A list of environment IDs associated with this listening tentacle.
        /// </summary>
        public readonly ImmutableArray<string> Environments;
        public readonly bool HasLatestCalamari;
        /// <summary>
        /// Represents the health status of this deployment target. Valid health statuses are `HasWarnings`, `Healthy`, `Unavailable`, `Unhealthy`, or `Unknown`.
        /// </summary>
        public readonly string HealthStatus;
        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Represents the disabled status of this deployment target.
        /// </summary>
        public readonly bool IsDisabled;
        /// <summary>
        /// Represents the in-process status of this deployment target.
        /// </summary>
        public readonly bool IsInProcess;
        /// <summary>
        /// The machine policy ID that is associated with this deployment target.
        /// </summary>
        public readonly string MachinePolicyId;
        /// <summary>
        /// The name of this resource.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The operating system that is associated with this deployment target.
        /// </summary>
        public readonly string OperatingSystem;
        /// <summary>
        /// The proxy ID that is associated with this deployment target.
        /// </summary>
        public readonly string ProxyId;
        /// <summary>
        /// A list of role IDs that are associated with this deployment target.
        /// </summary>
        public readonly ImmutableArray<string> Roles;
        /// <summary>
        /// The shell name associated with this deployment target.
        /// </summary>
        public readonly string ShellName;
        /// <summary>
        /// The shell version associated with this deployment target.
        /// </summary>
        public readonly string ShellVersion;
        /// <summary>
        /// The space ID associated with this resource.
        /// </summary>
        public readonly string SpaceId;
        /// <summary>
        /// The status of this resource. Valid statuses are `CalamariNeedsUpgrade`, `Disabled`, `NeedsUpgrade`, `Offline`, `Online`, or `Unknown`.
        /// </summary>
        public readonly string Status;
        /// <summary>
        /// A summary elaborating on the status of this resource.
        /// </summary>
        public readonly string StatusSummary;
        /// <summary>
        /// A list of tenant tags associated with this resource.
        /// </summary>
        public readonly ImmutableArray<string> TenantTags;
        /// <summary>
        /// The tenanted deployment mode of the resource. Valid account types are `Untenanted`, `TenantedOrUntenanted`, or `Tenanted`.
        /// </summary>
        public readonly string TenantedDeploymentParticipation;
        /// <summary>
        /// A list of tenant IDs associated with this resource.
        /// </summary>
        public readonly ImmutableArray<string> Tenants;
        /// <summary>
        /// The tenant URL of this deployment target.
        /// </summary>
        public readonly string TentacleUrl;
        public readonly ImmutableArray<Outputs.GetListeningTentacleDeploymentTargetsListeningTentacleDeploymentTargetTentacleVersionDetailResult> TentacleVersionDetails;
        /// <summary>
        /// The thumbprint of this deployment target.
        /// </summary>
        public readonly string Thumbprint;
        /// <summary>
        /// The URI of this deployment target.
        /// </summary>
        public readonly string Uri;

        [OutputConstructor]
        private GetListeningTentacleDeploymentTargetsListeningTentacleDeploymentTargetResult(
            string certificateSignatureAlgorithm,

            ImmutableArray<string> environments,

            bool hasLatestCalamari,

            string healthStatus,

            string id,

            bool isDisabled,

            bool isInProcess,

            string machinePolicyId,

            string name,

            string operatingSystem,

            string proxyId,

            ImmutableArray<string> roles,

            string shellName,

            string shellVersion,

            string spaceId,

            string status,

            string statusSummary,

            ImmutableArray<string> tenantTags,

            string tenantedDeploymentParticipation,

            ImmutableArray<string> tenants,

            string tentacleUrl,

            ImmutableArray<Outputs.GetListeningTentacleDeploymentTargetsListeningTentacleDeploymentTargetTentacleVersionDetailResult> tentacleVersionDetails,

            string thumbprint,

            string uri)
        {
            CertificateSignatureAlgorithm = certificateSignatureAlgorithm;
            Environments = environments;
            HasLatestCalamari = hasLatestCalamari;
            HealthStatus = healthStatus;
            Id = id;
            IsDisabled = isDisabled;
            IsInProcess = isInProcess;
            MachinePolicyId = machinePolicyId;
            Name = name;
            OperatingSystem = operatingSystem;
            ProxyId = proxyId;
            Roles = roles;
            ShellName = shellName;
            ShellVersion = shellVersion;
            SpaceId = spaceId;
            Status = status;
            StatusSummary = statusSummary;
            TenantTags = tenantTags;
            TenantedDeploymentParticipation = tenantedDeploymentParticipation;
            Tenants = tenants;
            TentacleUrl = tentacleUrl;
            TentacleVersionDetails = tentacleVersionDetails;
            Thumbprint = thumbprint;
            Uri = uri;
        }
    }
}
