// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class GetLifecyclesLifecyclePhaseResult
    {
        public readonly ImmutableArray<string> AutomaticDeploymentTargets;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;
        public readonly bool? IsOptionalPhase;
        public readonly int? MinimumEnvironmentsBeforePromotion;
        public readonly string Name;
        public readonly ImmutableArray<string> OptionalDeploymentTargets;
        public readonly Outputs.GetLifecyclesLifecyclePhaseReleaseRetentionPolicyResult? ReleaseRetentionPolicy;
        public readonly Outputs.GetLifecyclesLifecyclePhaseTentacleRetentionPolicyResult? TentacleRetentionPolicy;

        [OutputConstructor]
        private GetLifecyclesLifecyclePhaseResult(
            ImmutableArray<string> automaticDeploymentTargets,

            string id,

            bool? isOptionalPhase,

            int? minimumEnvironmentsBeforePromotion,

            string name,

            ImmutableArray<string> optionalDeploymentTargets,

            Outputs.GetLifecyclesLifecyclePhaseReleaseRetentionPolicyResult? releaseRetentionPolicy,

            Outputs.GetLifecyclesLifecyclePhaseTentacleRetentionPolicyResult? tentacleRetentionPolicy)
        {
            AutomaticDeploymentTargets = automaticDeploymentTargets;
            Id = id;
            IsOptionalPhase = isOptionalPhase;
            MinimumEnvironmentsBeforePromotion = minimumEnvironmentsBeforePromotion;
            Name = name;
            OptionalDeploymentTargets = optionalDeploymentTargets;
            ReleaseRetentionPolicy = releaseRetentionPolicy;
            TentacleRetentionPolicy = tentacleRetentionPolicy;
        }
    }
}
