// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class GetTeamsTeamResult
    {
        public readonly bool CanBeDeleted;
        public readonly bool CanBeRenamed;
        public readonly bool CanChangeMembers;
        public readonly bool CanChangeRoles;
        /// <summary>
        /// The user-friendly description of this team.
        /// </summary>
        public readonly string Description;
        public readonly ImmutableArray<Outputs.GetTeamsTeamExternalSecurityGroupResult> ExternalSecurityGroups;
        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of this team.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The space associated with this team.
        /// </summary>
        public readonly string SpaceId;
        /// <summary>
        /// A list of user IDs designated to be members of this team.
        /// </summary>
        public readonly ImmutableArray<string> Users;

        [OutputConstructor]
        private GetTeamsTeamResult(
            bool canBeDeleted,

            bool canBeRenamed,

            bool canChangeMembers,

            bool canChangeRoles,

            string description,

            ImmutableArray<Outputs.GetTeamsTeamExternalSecurityGroupResult> externalSecurityGroups,

            string id,

            string name,

            string spaceId,

            ImmutableArray<string> users)
        {
            CanBeDeleted = canBeDeleted;
            CanBeRenamed = canBeRenamed;
            CanChangeMembers = canChangeMembers;
            CanChangeRoles = canChangeRoles;
            Description = description;
            ExternalSecurityGroups = externalSecurityGroups;
            Id = id;
            Name = name;
            SpaceId = spaceId;
            Users = users;
        }
    }
}
