// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class TeamExternalSecurityGroup
    {
        public readonly bool? DisplayIdAndName;
        public readonly string? DisplayName;
        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        public readonly string? Id;

        [OutputConstructor]
        private TeamExternalSecurityGroup(
            bool? displayIdAndName,

            string? displayName,

            string? id)
        {
            DisplayIdAndName = displayIdAndName;
            DisplayName = displayName;
            Id = id;
        }
    }
}
