// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Octopusdeploy.Outputs
{

    [OutputType]
    public sealed class VariableScope
    {
        /// <summary>
        /// A list of actions that are scoped to this variable value.
        /// </summary>
        public readonly ImmutableArray<string> Actions;
        /// <summary>
        /// A list of channels that are scoped to this variable value.
        /// </summary>
        public readonly ImmutableArray<string> Channels;
        /// <summary>
        /// A list of environments that are scoped to this variable value.
        /// </summary>
        public readonly ImmutableArray<string> Environments;
        /// <summary>
        /// A list of machines that are scoped to this variable value.
        /// </summary>
        public readonly ImmutableArray<string> Machines;
        /// <summary>
        /// A list of roles that are scoped to this variable value.
        /// </summary>
        public readonly ImmutableArray<string> Roles;
        /// <summary>
        /// A list of tenant tags that are scoped to this variable value.
        /// </summary>
        public readonly ImmutableArray<string> TenantTags;

        [OutputConstructor]
        private VariableScope(
            ImmutableArray<string> actions,

            ImmutableArray<string> channels,

            ImmutableArray<string> environments,

            ImmutableArray<string> machines,

            ImmutableArray<string> roles,

            ImmutableArray<string> tenantTags)
        {
            Actions = actions;
            Channels = channels;
            Environments = environments;
            Machines = machines;
            Roles = roles;
            TenantTags = tenantTags;
        }
    }
}
