// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Octopusdeploy.Inputs
{

    public sealed class GetEnvironmentsEnvironmentJiraServiceManagementExtensionSettingInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("isEnabled", required: true)]
        public Input<bool> IsEnabled { get; set; } = null!;

        public GetEnvironmentsEnvironmentJiraServiceManagementExtensionSettingInputArgs()
        {
        }
        public static new GetEnvironmentsEnvironmentJiraServiceManagementExtensionSettingInputArgs Empty => new GetEnvironmentsEnvironmentJiraServiceManagementExtensionSettingInputArgs();
    }
}
