// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Octopusdeploy.Inputs
{

    public sealed class GetLibraryVariableSetsLibraryVariableSetArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The description of this library variable set.
        /// </summary>
        [Input("description", required: true)]
        public string Description { get; set; } = null!;

        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// The name of this resource.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        /// <summary>
        /// The space ID associated with this resource.
        /// </summary>
        [Input("spaceId", required: true)]
        public string SpaceId { get; set; } = null!;

        [Input("templates", required: true)]
        private List<Inputs.GetLibraryVariableSetsLibraryVariableSetTemplateArgs>? _templates;
        public List<Inputs.GetLibraryVariableSetsLibraryVariableSetTemplateArgs> Templates
        {
            get => _templates ?? (_templates = new List<Inputs.GetLibraryVariableSetsLibraryVariableSetTemplateArgs>());
            set => _templates = value;
        }

        [Input("variableSetId", required: true)]
        public string VariableSetId { get; set; } = null!;

        public GetLibraryVariableSetsLibraryVariableSetArgs()
        {
        }
        public static new GetLibraryVariableSetsLibraryVariableSetArgs Empty => new GetLibraryVariableSetsLibraryVariableSetArgs();
    }
}
