// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Octopusdeploy.Inputs
{

    public sealed class GetMachinePoliciesMachinePolicyInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("connectionConnectTimeout", required: true)]
        public Input<int> ConnectionConnectTimeout { get; set; } = null!;

        [Input("connectionRetryCountLimit", required: true)]
        public Input<int> ConnectionRetryCountLimit { get; set; } = null!;

        [Input("connectionRetrySleepInterval", required: true)]
        public Input<int> ConnectionRetrySleepInterval { get; set; } = null!;

        [Input("connectionRetryTimeLimit", required: true)]
        public Input<int> ConnectionRetryTimeLimit { get; set; } = null!;

        /// <summary>
        /// The description of this machine policy.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        [Input("isDefault", required: true)]
        public Input<bool> IsDefault { get; set; } = null!;

        [Input("machineCleanupPolicies", required: true)]
        private InputList<Inputs.GetMachinePoliciesMachinePolicyMachineCleanupPolicyInputArgs>? _machineCleanupPolicies;
        public InputList<Inputs.GetMachinePoliciesMachinePolicyMachineCleanupPolicyInputArgs> MachineCleanupPolicies
        {
            get => _machineCleanupPolicies ?? (_machineCleanupPolicies = new InputList<Inputs.GetMachinePoliciesMachinePolicyMachineCleanupPolicyInputArgs>());
            set => _machineCleanupPolicies = value;
        }

        [Input("machineConnectivityPolicies", required: true)]
        private InputList<Inputs.GetMachinePoliciesMachinePolicyMachineConnectivityPolicyInputArgs>? _machineConnectivityPolicies;
        public InputList<Inputs.GetMachinePoliciesMachinePolicyMachineConnectivityPolicyInputArgs> MachineConnectivityPolicies
        {
            get => _machineConnectivityPolicies ?? (_machineConnectivityPolicies = new InputList<Inputs.GetMachinePoliciesMachinePolicyMachineConnectivityPolicyInputArgs>());
            set => _machineConnectivityPolicies = value;
        }

        [Input("machineHealthCheckPolicies", required: true)]
        private InputList<Inputs.GetMachinePoliciesMachinePolicyMachineHealthCheckPolicyInputArgs>? _machineHealthCheckPolicies;
        public InputList<Inputs.GetMachinePoliciesMachinePolicyMachineHealthCheckPolicyInputArgs> MachineHealthCheckPolicies
        {
            get => _machineHealthCheckPolicies ?? (_machineHealthCheckPolicies = new InputList<Inputs.GetMachinePoliciesMachinePolicyMachineHealthCheckPolicyInputArgs>());
            set => _machineHealthCheckPolicies = value;
        }

        [Input("machineUpdatePolicies", required: true)]
        private InputList<Inputs.GetMachinePoliciesMachinePolicyMachineUpdatePolicyInputArgs>? _machineUpdatePolicies;
        public InputList<Inputs.GetMachinePoliciesMachinePolicyMachineUpdatePolicyInputArgs> MachineUpdatePolicies
        {
            get => _machineUpdatePolicies ?? (_machineUpdatePolicies = new InputList<Inputs.GetMachinePoliciesMachinePolicyMachineUpdatePolicyInputArgs>());
            set => _machineUpdatePolicies = value;
        }

        /// <summary>
        /// The name of this resource.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("pollingRequestMaximumMessageProcessingTimeout", required: true)]
        public Input<int> PollingRequestMaximumMessageProcessingTimeout { get; set; } = null!;

        [Input("pollingRequestQueueTimeout", required: true)]
        public Input<int> PollingRequestQueueTimeout { get; set; } = null!;

        /// <summary>
        /// The space ID associated with this resource.
        /// </summary>
        [Input("spaceId", required: true)]
        public Input<string> SpaceId { get; set; } = null!;

        public GetMachinePoliciesMachinePolicyInputArgs()
        {
        }
        public static new GetMachinePoliciesMachinePolicyInputArgs Empty => new GetMachinePoliciesMachinePolicyInputArgs();
    }
}
