// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Octopusdeploy.Inputs
{

    public sealed class GetProjectsProjectReleaseCreationStrategyReleaseCreationPackageArgs : global::Pulumi.InvokeArgs
    {
        [Input("deploymentAction")]
        public string? DeploymentAction { get; set; }

        [Input("packageReference")]
        public string? PackageReference { get; set; }

        public GetProjectsProjectReleaseCreationStrategyReleaseCreationPackageArgs()
        {
        }
        public static new GetProjectsProjectReleaseCreationStrategyReleaseCreationPackageArgs Empty => new GetProjectsProjectReleaseCreationStrategyReleaseCreationPackageArgs();
    }
}
