// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Inputs
{

    public sealed class GetSpacesSpaceInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The description of this space.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// Specifies if this space is the default space in Octopus.
        /// </summary>
        [Input("isDefault", required: true)]
        public Input<bool> IsDefault { get; set; } = null!;

        /// <summary>
        /// Specifies the status of the task queue for this space.
        /// </summary>
        [Input("isTaskQueueStopped", required: true)]
        public Input<bool> IsTaskQueueStopped { get; set; } = null!;

        /// <summary>
        /// The name of this resource, no more than 20 characters long
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// The unique slug of this space.
        /// </summary>
        [Input("slug", required: true)]
        public Input<string> Slug { get; set; } = null!;

        [Input("spaceManagersTeamMembers", required: true)]
        private InputList<string>? _spaceManagersTeamMembers;

        /// <summary>
        /// A list of user IDs designated to be managers of this space.
        /// </summary>
        public InputList<string> SpaceManagersTeamMembers
        {
            get => _spaceManagersTeamMembers ?? (_spaceManagersTeamMembers = new InputList<string>());
            set => _spaceManagersTeamMembers = value;
        }

        [Input("spaceManagersTeams", required: true)]
        private InputList<string>? _spaceManagersTeams;

        /// <summary>
        /// A list of team IDs designated to be managers of this space.
        /// </summary>
        public InputList<string> SpaceManagersTeams
        {
            get => _spaceManagersTeams ?? (_spaceManagersTeams = new InputList<string>());
            set => _spaceManagersTeams = value;
        }

        public GetSpacesSpaceInputArgs()
        {
        }
        public static new GetSpacesSpaceInputArgs Empty => new GetSpacesSpaceInputArgs();
    }
}
