// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Octopusdeploy.Inputs
{

    public sealed class GetTenantsTenantArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the tenant from which this tenant was cloned.
        /// </summary>
        [Input("clonedFromTenantId", required: true)]
        public string ClonedFromTenantId { get; set; } = null!;

        /// <summary>
        /// The description of this tenant.
        /// </summary>
        [Input("description", required: true)]
        public string Description { get; set; } = null!;

        /// <summary>
        /// The unique ID for this resource.
        /// </summary>
        [Input("id", required: true)]
        public string Id { get; set; } = null!;

        /// <summary>
        /// The name of this resource.
        /// </summary>
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        [Input("projectEnvironments", required: true)]
        private List<Inputs.GetTenantsTenantProjectEnvironmentArgs>? _projectEnvironments;
        public List<Inputs.GetTenantsTenantProjectEnvironmentArgs> ProjectEnvironments
        {
            get => _projectEnvironments ?? (_projectEnvironments = new List<Inputs.GetTenantsTenantProjectEnvironmentArgs>());
            set => _projectEnvironments = value;
        }

        /// <summary>
        /// The space ID associated with this resource.
        /// </summary>
        [Input("spaceId", required: true)]
        public string SpaceId { get; set; } = null!;

        [Input("tenantTags", required: true)]
        private List<string>? _tenantTags;

        /// <summary>
        /// A list of tenant tags associated with this resource.
        /// </summary>
        public List<string> TenantTags
        {
            get => _tenantTags ?? (_tenantTags = new List<string>());
            set => _tenantTags = value;
        }

        public GetTenantsTenantArgs()
        {
        }
        public static new GetTenantsTenantArgs Empty => new GetTenantsTenantArgs();
    }
}
