// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace PiersKarsenbarg.Octopusdeploy.Inputs
{

    public sealed class ProjectServicenowExtensionSettingsGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The connection identifier associated with the extension settings.
        /// </summary>
        [Input("connectionId", required: true)]
        public Input<string> ConnectionId { get; set; } = null!;

        /// <summary>
        /// Specifies whether or not this extension is enabled for this project.
        /// </summary>
        [Input("isEnabled", required: true)]
        public Input<bool> IsEnabled { get; set; } = null!;

        /// <summary>
        /// Specifies whether or not this extension will automatically transition the state of a deployment for this project.
        /// </summary>
        [Input("isStateAutomaticallyTransitioned", required: true)]
        public Input<bool> IsStateAutomaticallyTransitioned { get; set; } = null!;

        /// <summary>
        /// The name of the standard change template associated with this extension.
        /// </summary>
        [Input("standardChangeTemplateName", required: true)]
        public Input<string> StandardChangeTemplateName { get; set; } = null!;

        public ProjectServicenowExtensionSettingsGetArgs()
        {
        }
        public static new ProjectServicenowExtensionSettingsGetArgs Empty => new ProjectServicenowExtensionSettingsGetArgs();
    }
}
