// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides information about existing feeds.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as octopusdeploy from "@pulumi/octopusdeploy";
 *
 * const example = octopusdeploy.getFeeds({
 *     feedType: "NuGet",
 *     ids: [
 *         "Feeds-123",
 *         "Feeds-321",
 *     ],
 *     partialName: "Develop",
 *     skip: 5,
 *     take: 100,
 * });
 * ```
 */
export function getFeeds(args?: GetFeedsArgs, opts?: pulumi.InvokeOptions): Promise<GetFeedsResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("octopusdeploy:index/getFeeds:getFeeds", {
        "feedType": args.feedType,
        "feeds": args.feeds,
        "ids": args.ids,
        "name": args.name,
        "partialName": args.partialName,
        "skip": args.skip,
        "take": args.take,
    }, opts);
}

/**
 * A collection of arguments for invoking getFeeds.
 */
export interface GetFeedsArgs {
    /**
     * A filter to search by feed type. Valid feed types are `AwsElasticContainerRegistry`, `BuiltIn`, `Docker`, `GitHub`, `Helm`, `Maven`, `NuGet`, or `OctopusProject`.
     */
    feedType?: string;
    /**
     * A list of feeds that match the filter(s).
     */
    feeds?: inputs.GetFeedsFeed[];
    /**
     * A filter to search by a list of IDs.
     */
    ids?: string[];
    /**
     * A filter to search by name.
     */
    name?: string;
    /**
     * A filter to search by the partial match of a name.
     */
    partialName?: string;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    skip?: number;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    take?: number;
}

/**
 * A collection of values returned by getFeeds.
 */
export interface GetFeedsResult {
    /**
     * A filter to search by feed type. Valid feed types are `AwsElasticContainerRegistry`, `BuiltIn`, `Docker`, `GitHub`, `Helm`, `Maven`, `NuGet`, or `OctopusProject`.
     */
    readonly feedType?: string;
    /**
     * A list of feeds that match the filter(s).
     */
    readonly feeds: outputs.GetFeedsFeed[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * A filter to search by a list of IDs.
     */
    readonly ids?: string[];
    /**
     * A filter to search by name.
     */
    readonly name?: string;
    /**
     * A filter to search by the partial match of a name.
     */
    readonly partialName?: string;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    readonly skip?: number;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    readonly take?: number;
}
/**
 * Provides information about existing feeds.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as octopusdeploy from "@pulumi/octopusdeploy";
 *
 * const example = octopusdeploy.getFeeds({
 *     feedType: "NuGet",
 *     ids: [
 *         "Feeds-123",
 *         "Feeds-321",
 *     ],
 *     partialName: "Develop",
 *     skip: 5,
 *     take: 100,
 * });
 * ```
 */
export function getFeedsOutput(args?: GetFeedsOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetFeedsResult> {
    return pulumi.output(args).apply((a: any) => getFeeds(a, opts))
}

/**
 * A collection of arguments for invoking getFeeds.
 */
export interface GetFeedsOutputArgs {
    /**
     * A filter to search by feed type. Valid feed types are `AwsElasticContainerRegistry`, `BuiltIn`, `Docker`, `GitHub`, `Helm`, `Maven`, `NuGet`, or `OctopusProject`.
     */
    feedType?: pulumi.Input<string>;
    /**
     * A list of feeds that match the filter(s).
     */
    feeds?: pulumi.Input<pulumi.Input<inputs.GetFeedsFeedArgs>[]>;
    /**
     * A filter to search by a list of IDs.
     */
    ids?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A filter to search by name.
     */
    name?: pulumi.Input<string>;
    /**
     * A filter to search by the partial match of a name.
     */
    partialName?: pulumi.Input<string>;
    /**
     * A filter to specify the number of items to skip in the response.
     */
    skip?: pulumi.Input<number>;
    /**
     * A filter to specify the number of items to take (or return) in the response.
     */
    take?: pulumi.Input<number>;
}
